In [3]:
%run important-functions.ipynb
import pandas as pd
import numpy as np
import matplotlib as mpl

c:\Users\Administrador\anaconda3\lib\site-packages\nbformat\__init__.py:92: MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)

Some important vertex and facets table plots are shown here.

In [6]:
CHSH_vertex_df = pd.read_csv("Bell_scenarios_data/scenario_2by2_chsh/CHSH_vertex.csv")
display(CHSH_vertex_df)

    d  a_0  a_1  b_0  b_1  E00  E01  E10  E11
0   1   -1   -1   -1   -1    1    1    1    1
1   1   -1   -1   -1    1    1   -1    1   -1
2   1   -1   -1    1   -1   -1    1   -1    1
3   1   -1   -1    1    1   -1   -1   -1   -1
4   1   -1    1   -1   -1    1    1   -1   -1
5   1   -1    1   -1    1    1   -1   -1    1
6   1   -1    1    1   -1   -1    1    1   -1
7   1   -1    1    1    1   -1   -1    1    1
8   1    1   -1   -1   -1   -1   -1    1    1
9   1    1   -1   -1    1   -1    1    1   -1
10  1    1   -1    1   -1    1   -1   -1    1
11  1    1   -1    1    1    1    1   -1   -1
12  1    1    1   -1   -1   -1   -1   -1   -1
13  1    1    1   -1    1   -1    1   -1    1
14  1    1    1    1   -1    1   -1    1   -1
15  1    1    1    1    1    1    1    1    1

In [7]:
CHSH_facets_df = pd.read_csv("Bell_scenarios_data/scenario_2by2_chsh/CHSH_facets_df.csv")
display(CHSH_facets_df)

    d  a_0  a_1  b_0  b_1  E00  E01  E10  E11
0   1   -1    0   -1    0    1    0    0    0
1   1   -1    0    0   -1    0    1    0    0
2   1    0   -1   -1    0    0    0    1    0
3   1    0   -1    0   -1    0    0    0    1
4   1   -1    0    0    1    0   -1    0    0
5   1   -1    0    1    0   -1    0    0    0
6   2    0    0    0    0   -1   -1   -1    1
7   2    0    0    0    0   -1   -1    1   -1
8   1    0   -1    0    1    0    0    0   -1
9   1    0   -1    1    0    0    0   -1    0
10  2    0    0    0    0   -1    1   -1   -1
11  2    0    0    0    0    1   -1   -1   -1
12  1    0    1   -1    0    0    0   -1    0
13  1    1    0   -1    0   -1    0    0    0
14  1    0    1    0   -1    0    0    0   -1
15  1    1    0    0   -1    0   -1    0    0
16  1    0    1    0    1    0    0    0    1
17  2    0    0    0    0   -1    1    1    1
18  1    0    1    1    0    0    0    1    0
19  2    0    0    0    0    1   -1    1    1
20  1    1    0    0    1    0    1    0    0
21  2    0    0    0    0    1    1   -1    1
22  1    1    0    1    0    1    0    0    0
23  2    0    0    0    0    1    1    1   -1

In [4]:
CH_vertex_df = pd.read_csv("Bell_scenarios_data/scenario_2by2_ch/CH_vertex_df.csv")
display(CH_vertex_df)

,d,p(a=0|x=0),p(a=0|x=1),p(b=0|y=0),p(b=0|y=1),p(00|00),p(01|00),p(10|00),p(11|00)
0,1,0,0,0,0,0,0,0,0
1,1,0,0,0,1,0,0,0,0
2,1,0,0,1,0,0,0,0,0
3,1,0,0,1,1,0,0,0,0
4,1,0,1,0,0,0,0,0,0
5,1,0,1,0,1,0,0,0,1
6,1,0,1,1,0,0,0,1,0
7,1,0,1,1,1,0,0,1,1
8,1,1,0,0,0,0,0,0,0
9,1,1,0,0,1,0,1,0,0
10,1,1,0,1,0,1,0,0,0
11,1,1,0,1,1,1,1,0,0
12,1,1,1,0,0,0,0,0,0
13,1,1,1,0,1,0,1,0,1
14,1,1,1,1,0,1,0,1,0
15,1,1,1,1,1,1,1,1,1

In [9]:
CH_facets_df = pd.read_csv("Bell_scenarios/scenario_2by2_ch/CH_facets_df.csv")
display(CH_facets_df)

,d,p(a=0|x=0),p(a=0|x=1),p(b=0|y=0),p(b=0|y=1),p(00|00),p(00|01),p(00|10),p(00|11)
0,1,-1,0,-1,0,1,0,0,0
1,1,-1,0,0,-1,0,1,0,0
2,1,0,-1,-1,0,0,0,1,0
3,1,0,-1,0,-1,0,0,0,1
4,0,0,0,0,1,0,-1,0,0
5,0,0,0,1,0,-1,0,0,0
6,0,1,0,1,0,-1,-1,-1,1
7,0,1,0,0,1,-1,-1,1,-1
8,0,0,0,0,1,0,0,0,-1
9,0,0,0,1,0,0,0,-1,0
10,0,0,1,1,0,-1,1,-1,-1
11,0,0,1,0,1,1,-1,-1,-1
12,0,0,1,0,0,0,0,-1,0
13,0,1,0,0,0,-1,0,0,0
14,0,0,1,0,0,0,0,0,-1
15,0,1,0,0,0,0,-1,0,0
16,0,0,0,0,0,0,0,0,1
17,1,0,-1,0,-1,-1,1,1,1
18,0,0,0,0,0,0,0,1,0
19,1,0,-1,-1,0,1,-1,1,1
20,0,0,0,0,0,0,1,0,0
21,1,-1,0,0,-1,1,1,-1,1
22,0,0,0,0,0,1,0,0,0
23,1,-1,0,-1,0,1,1,1,-1